### ISSUE TITLE
Coproc packet framing

### ISSUE THREAD

**Issue by dzarda** [RoboticsBrno/RB3204-RBCX#14]
Dedicate a new UART as a transceiver of packets with a fixed prefix.

Nanopb provides length-prefixed encode/decode, so this doesn't have to be solved here.

Required for #13

**Comment by yaqwsx** [comment]
Is there a suitable counterpart of the encoding for desktops? Or do we have to implement it ourselves on the desktop?

Otherwise, I agree with usage of encoding provided by Nanopb.

**Comment by dzarda** [comment]
We'll need to make a converter for desktops. I'm thinking like

There's things that implement the COBS encoding like libspf, but I think that's an overkill. PB3 doesn't send zero values, and zero bytes shouldn't appear on the wire unless present in 'bytes' and the like

So I think we may simply use 0x00 as the packet terminator. Together with some timeout, it should be robust enough IMO.

**Comment by dzarda** [comment]
> and zero bytes shouldn't appear on the wire

Of course I messed up somewhat - the `fixed` types will contain zeros verbatim

**Comment by dzarda** [comment]
More thinking done - I feel like I want the COBS encoding so that zero bytes are only present as packet terminators. Would allow time invariance in receive logic and better robustness imo.

Seems like there's things available OOTB for C and py.

**Comment by yaqwsx** [comment]
You are more experienced in this area and by briefly looking, it looks nice. So, go for it and let's use it.
