### ISSUE TITLE
Periferie na tábor

### ISSUE THREAD

**Issue by Tasssadar** [RoboticsBrno/RB3204-RBCX#21]
Seznam toho, co musí fungovat na Robotku na tábor (i.e. co je potřeba prioritizovat):

**STM:**
- [x] Vypínání, zapínání tlačítka
- [x] Tunel USB na desce -> programování ESP
- [x] Vypínání ze SW
- [x] Napětí na baterii, samovypínání
- [x] Watchdog ESP32 (jestli nespadlo, nezaseklo se)
- [x] Ledky
- [x] Tlačítka
- [x] Motory
- [x] Enkodéry
- [x] Ultrazvuk
- [x] Serva
- [x] Piezo

**ESP32**
- [x] Inteligentní ledky
- [x] ČínaČára senzory

**Comment by dzarda** [comment]
Aha pardon, tohle už je výběr a checkboxy mají signalizovat dokončenost...
