### ISSUE TITLE
Zprovoznit programování přes tunel

### ISSUE THREAD

**Issue by dzarda** [RoboticsBrno/RB3204-RBCX#24]
USB tunel už je v STM implementován pomocí dmitrystu/libusb_stm32. Má to ale lehké mouchy:
- V downstream kanálu dochází ke ztrátě dat, když se naráz pošle víc jak 64b (velikost EP). Řešeno v https://github.com/dmitrystu/libusb_stm32/issues/51
- Je nastaveno fixně 115200, lze řešit v `cdc_control ... case USB_CDC_SET_LINE_CODING:`
- UART je stále aktivní nezávisle na připojení CDC

Asi nejdřív třeba vyzkoušet, jestli to v aktuálním stavu už náhodou nejde naprogramovat.

**Comment by Tasssadar** [comment]
Ano, a chtěl bych tam přidat i to nastavování rychlosti UARTu, jinak to bude těch 115200 při programování brzdit.

**Comment by cednik** [comment]
To by bylo super 👍
Jinak při ovládání těch pinů je potřeba implementovat následující tabulku [[1](https://dl.espressif.com/dl/schematics/esp32_devkitc_v4-sch.pdf)]:
![obrazek](https://user-images.githubusercontent.com/8156860/84006060-67ba9800-a96e-11ea-9420-d5ab941325d7.png)

Pak je potřeba si pohlídat úroveň na pinech [[2](https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32_datasheet_en.pdf#4)]
- STM PB15(SPI_MOSI/iLed) - ESP IO12 (MTDI/iLed): LOW
- STM v1.0 PC11(UART4_RX/control) v1.1 PD9(UART4_RX/control) - ESP IO2: LOW
