### ISSUE TITLE
hw_v1.1 changes

### ISSUE THREAD

**Issue by cednik** [RoboticsBrno/RB3204-RBCX#28]
- [x] Posunout dráhy měření proudu u serv dál od elektrolytů
- [x] Upravit pinout
- [x] Opravit popisky po změně pinoutu
- [x] Zmenšit zapínací kondenzátory (C5 100 nF, C6 2.2 uF)
- [x] Opravit fungování zapínacího tlačítka bez připojené baterky (napájení z USB)
- [x] Přidat Bmid na svorkovnici
- [ ] ~~Přidat rezistor mezi STM a power~~
- [x] Posunout součástky dál od pinheadů, kvůli pájení
- [x] Opravit masku u DRV8833 center padu
- [x] Zvětšit testpoit GND tak, aby do něj šel zapájet pinhead
- [x] Přesunout popisky pod piezzem
- [x] Nahradit GND_SEPARATOR cutout polygonem
- [x] Zmenšit velikost nastavovacích propojek
- [x] Upravit polygony napájení serv
- [ ] ~~Posunout testpointy dál od kondenzátorů~~ Není na to místo a stejně se k nim poleze zhora
- [x] Zkontrolovat thermaly
- [x] Upravit rozlití mědi kolem upevňovacích otvorů
- [x] Lehce roztáhnout piny USB-C
- [x] (Prohodit micro USB pinheadem, aby bylo místo na kabel vedle USB-C)
- [x] (Vytáhnout buzzer na pinhead)
- [x] (Vytágnout TP62 zpod ESP)
- [x] (Přidat tranzistor na zapínání iLed step-downu)
- [x] (Přehodit I2C na konektoru pro expandér)

**Comment by yaqwsx** [comment]
[ ] Zvážit odebrání grafiky na vstvách tPlace a bPlace ve footprintech. Podle [tohoto odkazu](https://electronics.stackexchange.com/questions/186324/what-is-the-difference-between-tplace-and-tdocu-layers-in-eagle-pcb) jsou tPlace a bPlace míněny jako vrstvy silkscreenu a KiCAD import je tak uvažuje. Jedná se o obdélníky okolo koprocesoru:

![Screenshot from 2020-06-09 08-47-29](https://user-images.githubusercontent.com/1590880/84115807-f858ad00-aa2e-11ea-83be-12e63a8b5c21.png)

**Comment by yaqwsx** [comment]
- [ ] Zvážit nepoužít mezery pro zarovnání textu, ale mít každý sloupeček jako samostatý text; rozbíjí KICAD import kvůli lehce jinému fontu:

![Screenshot from 2020-06-09 09-04-44](https://user-images.githubusercontent.com/1590880/84116763-b892c500-aa30-11ea-8d93-b9e20746abf9.png)
![Screenshot from 2020-06-09 09-06-31](https://user-images.githubusercontent.com/1590880/84116767-b92b5b80-aa30-11ea-8034-eb3ff6401094.png)

**Comment by cednik** [comment]
- [ ] Popisky svorkovnice zezadu (zepředu pod ní nejsou vidět)
- [ ] Přidat přepěťovou ochranu na měření prostředního článku

**Comment by cednik** [comment]
- [ ] Připojit gate Q8 na ESP_EN - fix pull-upu na IO12.

**Comment by dzarda** [comment]
[ ] Zvážit přidání pájecích ploch zboku USB konektorů pro lepší odolnost

![obrazek](https://user-images.githubusercontent.com/3955056/84895408-8e7d7a80-b0a2-11ea-96df-dbab6c3826e3.png)

**Comment by cednik** [comment]
Verze v1.1 vyrobena, zavírám.
