### ISSUE TITLE
Deploy FW na roboty

### ISSUE THREAD

**Issue by Tasssadar** [RoboticsBrno/RB3204-RBCX#33]
Jakým způsobem chceme dostávat FW na desky pro děti? 

1. Při oživování, normálně STLinkem
2. ???

**Comment by cednik** [comment]
Při oživování normálně STlinkem.
Další možnost je embeded bootloader skrze USART1 (USER).
V souvislosti s tím jsem přemýšlel, jestli neprohodit USER a CONTROL, ale asi se mi to nelíbí.
Krásný by byl USB bootloader 😇

**Comment by dzarda** [comment]
Tohle by mohlo být fajne https://github.com/dmitrystu/sboot_stm32

**Comment by dzarda** [comment]
Mega ultra by byl autoflash přes ESP při startu aplikace

**Comment by Tasssadar** [comment]
Bylo, ale bohužel to neřeší první flash, ten stejně asi bude muset být vždy ST-linkem :/

**Comment by dzarda** [comment]
Asi bude vhodnější to dělat přímo z PC (přes DFU nebo vystavíme control rozhraní i do PC)
