### ISSUE TITLE
CI + Code quality

### ISSUE THREAD

**Issue by JarekParal** [RoboticsBrno/RB3204-RBCX#6]
What do you think about adding CI for test builds and some Code quality tool, for checking the source code?

Also, we should use the [rb_clang_format](https://github.com/RoboticsBrno/rb_clang_format) and all convention from WebKit which we approved.

@dzarda @yaqwsx @cednik @Tasssadar

**Comment by dzarda** [comment]
First step should be just building the fw. Automatically checking code style seems tricky at this point IMHO

**Comment by JarekParal** [comment]
Yes, the first step is building ("adding CI for test builds"). But that should be easy with PlatformIO. We already have that on many repositories. 
Why do you think that checking code style is tricky? Also, we can use it just as advice tool. Not strong requirement.

**Comment by dzarda** [comment]
Tricky because I don't have best experience with it from work. Stuff fails on CI but not locally. Could be better with our workflow. Also there will be code in the repo (already is) that's not ours. Analyzer should ignore it.

**Comment by yaqwsx** [comment]
>Stuff fails on CI but not locally.

I think it is actually a good thing. CI verifies that you are not using some nuance of your local environment which the others cannot reproduce. Also CI "is the reference environment" which is easy to track and reproduce. Just to be clear - with PlatformIO there shouldn't be such problems.

To easily debug failures in remote, I started to run all my Travis CI in docker, which I can easily execute locally - see [an example](https://github.com/paradise-fi/RoFI/blob/master/.travis.yml). Docker also makes easy (and validated) tracking of development dependencies (see [corresponding Dockerfile](https://github.com/paradise-fi/RoFI/blob/master/Dockerfile)).

**Comment by dzarda** [comment]
Can we close this?

**Comment by JarekParal** [comment]
Yes, let's close this issue. CI is integrated and Code quality wouldn't be soo easy.
