### ISSUE TITLE
[CZ] USB DP pullup

### ISSUE THREAD

**Issue by dzarda** [RoboticsBrno/RB3204-RBCX#8]
STM32F1 zdá se nemá funkci pullupování DP 1k5 odporem. Co jsem pochopil, tak je to součástí enumerace Full Speed zařízení a dá se pomocí toho udělat "reconnect" - reenumerace, což bychom možná využili při přepnutí na JTAG (nebo možná by se dalo mít víc interfaces zaráz)

Bluepill má ten pullup asi natvrdo na +5V (což je asi blbě, čtu že to má být k 3V - 3V6)

Na našem schéma jsem to nenašel.

libusb tuhle funkci podporuje, dá se tomu port-pin.

**Comment by cednik** [comment]
Takže chceš jeden pin STM připojit přes 1k5 na USB DP?
To asi není problém.

**Comment by dzarda** [comment]
Už tam je, zavírám
